import { Inter } from 'next/font/google'
import '@radix-ui/themes/styles.css';
import './globals.css'
import NavBar from './components/NavBar'
import { Theme,ThemePanel } from '@radix-ui/themes';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <Theme appearance="light">
        
          <NavBar/>
          <main className="px-4 py-12 mx-auto">
            {children}
          </main>
        </Theme>
      </body>
    </html>
  )
}
