import { Inter } from 'next/font/google'
import '@radix-ui/themes/styles.css';
import './globals.css'
import NavBar from './components/NavBar'
import { Theme,ThemePanel } from '@radix-ui/themes';
import SideBar from './components/SideBar';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className + ' antialiased bg-gray-50 dark:bg-gray-800'} >
        <Theme>
          <NavBar/>
          <div className="flex pt-16 overflow-hidden bg-gray-50 dark:bg-gray-900">
            <SideBar />
            <div className="relative w-full h-full overflow-y-auto bg-gray-50 lg:ml-64 dark:bg-gray-900">
              
                
            {children}
              
            </div>
          </div>
        </Theme>
      </body>
    </html>
  )
}
